/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XRouteImport } from './routes/x'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmDottxtRouteImport } from './routes/llm[.]txt'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiFeedDotjsonRouteImport } from './routes/api.feed[.]json'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiBlogsRouteImport } from './routes/api.blogs'
import { Route as ApiBlogsSlugLikesRouteImport } from './routes/api.blogs.$slug.likes'
import { Route as ApiBlogsSlugCommentsRouteImport } from './routes/api.blogs.$slug.comments'

const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmDottxtRoute = LlmDottxtRouteImport.update({
  id: '/llm.txt',
  path: '/llm.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedDotjsonRoute = ApiFeedDotjsonRouteImport.update({
  id: '/api/feed.json',
  path: '/api/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsSlugLikesRoute = ApiBlogsSlugLikesRouteImport.update({
  id: '/$slug/likes',
  path: '/$slug/likes',
  getParentRoute: () => ApiBlogsRoute,
} as any)
const ApiBlogsSlugCommentsRoute = ApiBlogsSlugCommentsRouteImport.update({
  id: '/$slug/comments',
  path: '/$slug/comments',
  getParentRoute: () => ApiBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/book': typeof BookRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/feed.json': typeof ApiFeedDotjsonRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/blogs/$slug/comments': typeof ApiBlogsSlugCommentsRoute
  '/api/blogs/$slug/likes': typeof ApiBlogsSlugLikesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/book': typeof BookRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/feed.json': typeof ApiFeedDotjsonRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/blogs/$slug/comments': typeof ApiBlogsSlugCommentsRoute
  '/api/blogs/$slug/likes': typeof ApiBlogsSlugLikesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/book': typeof BookRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/x': typeof XRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/feed.json': typeof ApiFeedDotjsonRoute
  '/api/projects': typeof ApiProjectsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/blogs/$slug/comments': typeof ApiBlogsSlugCommentsRoute
  '/api/blogs/$slug/likes': typeof ApiBlogsSlugLikesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/book'
    | '/llm.txt'
    | '/llms.txt'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/x'
    | '/api/blogs'
    | '/api/chat'
    | '/api/contact'
    | '/api/feed.json'
    | '/api/projects'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/api/blogs/$slug/comments'
    | '/api/blogs/$slug/likes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/book'
    | '/llm.txt'
    | '/llms.txt'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/x'
    | '/api/blogs'
    | '/api/chat'
    | '/api/contact'
    | '/api/feed.json'
    | '/api/projects'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/api/blogs/$slug/comments'
    | '/api/blogs/$slug/likes'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/book'
    | '/llm.txt'
    | '/llms.txt'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/x'
    | '/api/blogs'
    | '/api/chat'
    | '/api/contact'
    | '/api/feed.json'
    | '/api/projects'
    | '/blogs/$slug'
    | '/projects/$slug'
    | '/api/blogs/$slug/comments'
    | '/api/blogs/$slug/likes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  BookRoute: typeof BookRoute
  LlmDottxtRoute: typeof LlmDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  XRoute: typeof XRoute
  ApiBlogsRoute: typeof ApiBlogsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiFeedDotjsonRoute: typeof ApiFeedDotjsonRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm.txt': {
      id: '/llm.txt'
      path: '/llm.txt'
      fullPath: '/llm.txt'
      preLoaderRoute: typeof LlmDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed.json': {
      id: '/api/feed.json'
      path: '/api/feed.json'
      fullPath: '/api/feed.json'
      preLoaderRoute: typeof ApiFeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs/$slug/likes': {
      id: '/api/blogs/$slug/likes'
      path: '/$slug/likes'
      fullPath: '/api/blogs/$slug/likes'
      preLoaderRoute: typeof ApiBlogsSlugLikesRouteImport
      parentRoute: typeof ApiBlogsRoute
    }
    '/api/blogs/$slug/comments': {
      id: '/api/blogs/$slug/comments'
      path: '/$slug/comments'
      fullPath: '/api/blogs/$slug/comments'
      preLoaderRoute: typeof ApiBlogsSlugCommentsRouteImport
      parentRoute: typeof ApiBlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ApiBlogsRouteChildren {
  ApiBlogsSlugCommentsRoute: typeof ApiBlogsSlugCommentsRoute
  ApiBlogsSlugLikesRoute: typeof ApiBlogsSlugLikesRoute
}

const ApiBlogsRouteChildren: ApiBlogsRouteChildren = {
  ApiBlogsSlugCommentsRoute: ApiBlogsSlugCommentsRoute,
  ApiBlogsSlugLikesRoute: ApiBlogsSlugLikesRoute,
}

const ApiBlogsRouteWithChildren = ApiBlogsRoute._addFileChildren(
  ApiBlogsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  BookRoute: BookRoute,
  LlmDottxtRoute: LlmDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  XRoute: XRoute,
  ApiBlogsRoute: ApiBlogsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiFeedDotjsonRoute: ApiFeedDotjsonRoute,
  ApiProjectsRoute: ApiProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
